universe = vanilla
executable = /mnt/ceph/home/park687/D01Ritz/scripts/analysis_job.sh
arguments = $(m) round1
initialdir = /mnt/ceph/home/park687/D01Ritz
should_transfer_files = YES
transfer_output_files = ""
getenv = False
when_to_transfer_output = ON_EXIT
requirements = (TARGET.IsOttenComputer =?= true) && (TARGET.Machine == "qis1.hep.wisc.edu")
+ProjectName = "UWMadison_Physics_Otten"
+ChtcProjects = "UWMadison_Physics_Otten"
+HEP_VO = "otten"
request_cpus = 1
request_memory = 4GB
request_disk = 1GB
output = work/scheduler/$(Cluster).$(Process).out
error = work/scheduler/$(Cluster).$(Process).err
log = work/scheduler/$(Cluster).log
+JobBatchName = "D01Ritz-analysis-20261006"
queue m from (
1000
10000
)
